# MCP Configuration for Story 5.2
# Professional Standards Framework Compliance - CEO Directive
# Implements secure MCP server connections and authentication

mcp_client:
  # Connection Configuration
  server_url: "ws://localhost:8000/mcp"
  authentication_token: null  # Set via environment variable MCP_AUTH_TOKEN
  
  # Timeout Configuration
  connection_timeout: 30.0  # seconds
  request_timeout: 10.0     # seconds
  
  # Retry Configuration  
  max_retries: 3
  retry_backoff: 1.0        # seconds
  max_backoff: 60.0         # seconds
  
  # Performance Configuration
  enable_compression: true
  max_connections: 10
  
  # Reliability Configuration
  circuit_breaker_threshold: 5    # failures before opening circuit
  circuit_breaker_timeout: 60.0   # seconds to wait before retry
  
  # Professional Standards Configuration
  enable_professional_validation: true
  enable_integrity_checks: true
  require_multi_agent_verification: true

# Text Processing Configuration
text_processing:
  # MCP Integration
  enable_mcp_processing: true
  enable_fallback: true
  
  # Context Classification
  context_types:
    - scriptural
    - idiomatic  
    - temporal
    - mathematical
    - general
    
  # Performance Targets
  min_processing_speed: 10.0  # segments per second
  max_response_time: 2.0      # seconds
  
  # Quality Assurance
  enable_qa_monitoring: true
  min_confidence_threshold: 0.7

# Monitoring Configuration
monitoring:
  enable_performance_metrics: true
  enable_health_checks: true
  metrics_collection_interval: 60.0  # seconds
  
  # Alert Thresholds
  alert_on_failure_rate: 0.1      # 10% failure rate
  alert_on_response_time: 5.0     # 5 second response time
  alert_on_circuit_breaker: true

# Security Configuration
security:
  enable_ssl_verification: true
  connection_encryption: true
  auth_token_rotation: false
  
# Development Configuration
development:
  enable_debug_logging: false
  mock_mcp_server: false
  local_fallback_mode: true
  
# Epic 4 Foundation Configuration
epic4_foundation:
  enable_extensible_patterns: true
  prepare_advanced_features: true
  document_integration_patterns: true