apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-post-processor
  namespace: production
  labels:
    app: asr-post-processor
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asr-post-processor
  template:
    metadata:
      labels:
        app: asr-post-processor
        version: v1.0.0
    spec:
      containers:
      - name: asr-post-processor
        image: asr-post-processor:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PYTHONPATH
          value: "/app/src"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
        - name: config-volume
          mountPath: /app/config/production
          readOnly: true
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: asr-data-pvc
      - name: logs-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: app-config
      restartPolicy: Always
      imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: asr-post-processor-service
  namespace: production
  labels:
    app: asr-post-processor
spec:
  selector:
    app: asr-post-processor
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  app_config.yaml: |
    processing:
      enable_performance_monitoring: true
      enable_logging: true
      batch_size: 100
      max_workers: 4
    
    text_normalization:
      enable_mcp_processing: true
      enable_monitoring: true
      enable_qa: true
    
    monitoring:
      metrics_enabled: true
      tracing_enabled: true
      health_checks_enabled: true
    
    security:
      enable_audit_logging: true
      enable_rate_limiting: true
      max_requests_per_minute: 1000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asr-data-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asr-post-processor-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asr-post-processor
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80